spring.profiles.active=prod

##RATE LIMITER

resilience4j.ratelimiter.instances.games.limit-for-period=3
resilience4j.ratelimiter.instances.games.limit-refresh-period=10s
resilience4j.ratelimiter.instances.games.timeout-duration=0s