spring.application.name=joga-together

## DB
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://postgres:5432/joga-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## Mail (MailHog - captura sem enviar)
spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.username=noreply@local.dev
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

## JWT
jwt.secret=am9nYS10b2dldGhlci1sb2NhbC1kZXYtc2VjcmV0ISE=
jwt.expiration-ms=3600000

## Spring Security debug - mostra EXATAMENTE por que 403
logging.level.org.springframework.security=DEBUG
logging.level.br.com.joga_together=DEBUG
